### ISSUE TITLE
Component Config tracking issue - aka. Modify configuration file format

### ISSUE THREAD

**Issue by kadisi** [kubeedge/kubeedge#1171]
**What would you like to be added/modified**:

Modify  configuration file format.

**Why is this needed**:

currently, cloudcore/edgecore/edgesite\`s configuration files are in the conf directory at the same level  and have 3 configuration files .It is difficult to maintain and extend。

The plan is to merge the three configuration files into one yaml file and analyze the configuration file like kubernetes instead of beehive.

ref #915 
ref #1086 
ref #522 

- [x] [proposal about modify  configuration file format](https://github.com/kubeedge/kubeedge/pull/1172)
- [x] [add edgecore, edgesite ,cloudcore apis ](https://github.com/kubeedge/kubeedge/pull/1212)
- [x] [change stop channel to golang context :cloudcore](https://github.com/kubeedge/kubeedge/pull/1215)
- [x] [change stop channel to golang context :edgecore](https://github.com/kubeedge/kubeedge/pull/1223)
- [x] [Optimize ci testcase for kubeedge](https://github.com/kubeedge/kubeedge/pull/1253)
- [x] [Modify the travis script to speed up the ci process](https://github.com/kubeedge/kubeedge/pull/1284)
- [x] [Optimize the initialization of the cloudcore module global variable](https://github.com/kubeedge/kubeedge/pull/1269)
- [x] [Optimize the initialization of the edgecore modules global variable](https://github.com/kubeedge/kubeedge/pull/1276)
- [x] [Optimize the use of beehive context ](https://github.com/kubeedge/kubeedge/pull/1262)
- [x] [Unified module source file naming convention](https://github.com/kubeedge/kubeedge/pull/1259)
- [x] [bugfix: Solve the problem of outputting a large amount of logs after edgecore exits](https://github.com/kubeedge/kubeedge/pull/1223)
- [x] [bugfix: Solve the problem of outputting a large amount of logs after cloudcore exits ](https://github.com/kubeedge/kubeedge/pull/1215)
- [ ] keadm conversion subcommand
- [x] change db install dir 
- [x] [edgecore --defaultconfig](https://github.com/kubeedge/kubeedge/pull/1399)
- [x] [cloudcore --defaultconfig](https://github.com/kubeedge/kubeedge/pull/1398)
- [x] [edgesite --defaultconfig](https://github.com/kubeedge/kubeedge/pull/1400)
- [x] **[modify kubeedge configuration file format](https://github.com/kubeedge/kubeedge/pull/1393)**
- [ ]  change Get() to CONFIG
- [ ]  update setup.md
- [ ]  change string type to ModuleName type `cloud/pkg/devicecontroller/messagelayer/context.go ContextMessageLayer`  and edgecontroller
- [ ]  print all config values for kubeedge compoment
- [ ] Unified definition of module name and group name
- [ ] integration_test: edgecore  Need to refactor integration_test
- [ ] e2e test for edgesite

**Comment by kadisi** [comment]
cc @kevin-wangzefeng @fisherxu @sids-b

**Comment by kevin-wangzefeng** [comment]
Todo for beta:
- [ ] PodSandboxImage - detect node architecture and pick corresponding image
