### ISSUE TITLE
Revising document structure

### ISSUE THREAD

**Issue by kevin-wangzefeng** [kubeedge/kubeedge#1498]
**What would you like to be added/modified**:

**Why is this needed**:
Existing document structure is not clean, we need to split user guide and developer guide, and relocate other content, to make it easier for reading.

relavent issues: #1334, #1340, #1119, #517, #944

**Tentantive content location**
```markdown
## user guide
  - one click install
  - install with keadm
  - running with managed k8s
  - play with a demo app (something like istio playbook)


## developer guide
  - build from code
  - trouble shooting
	

## concepts
  - arch
  - components
  - api objects
    - device model / device instance


## Reference (user manual, specifications)
  - ComponentConfigAPI
  - DeviceCRD
  - mapper design/develop specifications


## community
  - resources
    - meeting
    - notes
    - videos
    - mailing list, slack
  	
  - governance
    - membership
  	
  - release management
```

**Comment by daixiang0** [comment]
Add related issue: #1001 #517 #241

**Comment by daixiang0** [comment]
Here is the architecture of the new document:
```
# Welcome

## Getting Started

## Why KubeEdge

## RoadMap

# Setup

## Deploying

### Deploying using Keadm
### CloudCore & EdgeCore Config
### Deploying HA CloudCore

## Upgrading

# Feature

## Setting different container runtime with CRI

## Implement third party storage with CSI

## Run Kubectl logs/exec to debug pods on the edge

## Control resources on the edge with Admission

## Edge connection with EdgeMesh

## Run lightweight clusters on the edge with EdgeSite

# Architecture

## Common

### Beehive

## Cloud

### CloudHub
### EdgeController
### DeviceController

## Edge

### Edged
### EventBus
### MetaManager
### EdgeHub
### DeviceTwin
### ServiceBus

# Developer Guide

## Build

## Device CRD

Include Device Model and Device Instance.

## Mapper

Include Design, Usage and Implement guide.

## Message Topics

## Test

### Unit Test
### E2E Test
### Benchmark

## TroubleShooting

# Community

## Contributing

## Governance

## MemberShip

## Feature Lifecycle

## Release Manager

```

**Comment by daixiang0** [comment]
- [ ] Implement third party storage with CSI (https://github.com/kubeedge/website/issues/110)
- [ ] Control resources on the edge with Admission (https://github.com/kubeedge/website/issues/111)
- [ ] Create HTTP services with ServiceBus (https://github.com/kubeedge/website/issues/112)
- [ ] ServiceBus introducation (https://github.com/kubeedge/website/issues/113)
- [ ] Device CRD guide (https://github.com/kubeedge/website/issues/114)
- [ ] Mapper developer guide (https://github.com/kubeedge/website/issues/115)
