### ISSUE TITLE
Add advertise address for cloudcore

### ISSUE THREAD

**Issue by fisherxu** [kubeedge/kubeedge#1642]
We have added the feature of certificate issuance in kubeedge, and now we need to add a filed `advertise-address` to specify the service address of the cloudcore, which will be used in the SANs of the cloudcore certificate.

And now in cloudhub, websocket/quic all have [Address](https://github.com/kubeedge/kubeedge/blob/master/pkg/apis/componentconfig/cloudcore/v1alpha1/types.go#L117) field, when we add the `advertise -address`, is the `Address` in websocket/quic still needed?

The `advertise -address` will be a specific address like 1.2.3.4, but  `Address` in websocket/quic now default as `0.0.0.0`.

/cc @kevin-wangzefeng @kadisi @chendave @subpathdev  @GsssC @ls889 @XJangel 

Task List:
- [x] Add advertise address in cloudcore/cloudhub #1643
- [x] Update the docs for the usage of advertise address #1656 
- [ ] Add bind-address config option and remove address in websocket/quic/httpserver
- [x] Support config domain URL for cloudcore #2126

**Comment by kevin-wangzefeng** [comment]
When advertise-address added, the multiple `address` fields under websocket, quic, https etc. can be combined.

**Comment by kevin-wangzefeng** [comment]
> When `advertise-address` added, the multiple `address` fields under websocket, quic, https etc. can be combined.

The multiple `address` fields can be combined into e.g. `bind-address` under cloudhub config, `advertise-address` may need to be an array of ip addresses.

**Comment by fisherxu** [comment]
> The multiple address fields can be combined into e.g. bind-address under cloudhub config, advertise-address may need to be an array of ip addresses.

Yes, let's combine the multiple address fields to bind-address and make advertise-address an array, which has been added to the task list :)

**Comment by susu3621** [comment]
"Support config domain URL for cloudcore" is quite important, since the cloudcore may not have a static public ip.
Like the cloudcore may stay behind a DDNS gateway.
Without the URL support, seems we don't have method to deal with this case?
Is it still in our list?

**Comment by GsssC** [comment]
@XJangel can user config domain in cloudcore's ca now?

**Comment by ls889** [comment]
> @XJangel can user config domain in cloudcore's ca now?

ca? maybe you mean cert？

**Comment by GsssC** [comment]
@ls889 yes and welcome pr :)

**Comment by XJangel** [comment]
> "Support config domain URL for cloudcore" is quite important, since the cloudcore may not have a static public ip.
> Like the cloudcore may stay behind a DDNS gateway.
> Without the URL support, seems we don't have method to deal with this case?
> Is it still in our list?

yep, it is in the list and will be done these days.

**Comment by kevin-wangzefeng** [comment]
reopening as not all the tasks done.
/open

**Comment by ls889** [comment]
@fisherxu /cc  Please update the status of the tasks.  :)

**Comment by fisherxu** [comment]
> @fisherxu /cc Please update the status of the tasks. :)

Done. :)
