### ISSUE TITLE
EdgeMesh Known Issue

### ISSUE THREAD

**Issue by daixiang0** [kubeedge/kubeedge#1821]
It is a **summary** for known issue about EdgeMesh, no need to file any similiar issue like below:

- [x] EdgeMesh doc is not clear, like #1814, would fix by #1805
- [x] EdgeMesh test failed, like #1808 #1619 #1771, would fix by #1805
- [x] EdgeMesh run into panic, like #1436, would fix by #1843

/assign

**Comment by daixiang0** [comment]
Update
