### ISSUE TITLE
tracking issue about feature DMI

### ISSUE THREAD

**Issue by RyanZhaoXB** [kubeedge/kubeedge#3895]
hello guys. we have proposed an [issue](https://github.com/kubeedge/kubeedge/issues/3760) about DMI and we are working to implement it these days. here is the working plan for DMI and welcome to join us.

alpha version：
- [ ]  DMI Interface Adaptation @RyanZhaoXB 

1. provide DMI definition
2. the device operation logic of devicetwin in the original edgecore is modified to invoke the DMI interface.

- [ ] Device Manager provides REST access. @RyanZhaoXB 

1. create REST server
2. provides the handler function as a REST router.

- [ ] Mapper Management Interface Implementation @RyanZhaoXB 

1. mapper database structure design
2. register the mapper to the device manager and writes the mapper into the database.
4. obtaining mapper details interface
5. mapper health status check interface
6. obtain device information and configurations when the mapper is restarted

- [ ] create New Device Process @TianTianBigWang 

1. after receiving the configmap, the edgecore caches the configmap locally.
2. after receiving the device creation information, the edgecore invokes the DMI to create a device from the mapper.

- [ ] mapper implements the interface for adding, deleting, modifying, and querying devices. @TianTianBigWang 

1. interface for reporting device twin status
2. interface for deleting a device
4. the device status is periodically reported to the edgecore.
5. device status is synchronized from CloudCore to K8s.
6. interface for modifying device status

beta version：
- [ ] device reliability delivery capability

1. the syncController capability is reused to deliver device information reliably.

- [ ] device auto-discovery capability

1.  device discovery and registration automatically

- [ ] mapper implements data collection and device twin format sorting.

1. development  the demo of the data collection module (the existing mapper code can be reused)
2. develop the device twin module demo to parse device-related CRD information. (The existing Mapper code can be reused.)

- [ ] data service delivery capability

1. feature gate switch
2. start the backend REST Server.
3. mapper interconnects with Service and EdgeMesh for adaptation.
4. CloudCore automatically creates a service.
5. mapper management
6. data modification interface

- [ ] data push capability: mapper supports configuration of destination addresses and data push.

1. feature gate switch
2. interface for configuring destination rule routing rules
3. data forwarding capability of the destination rule
4. capabilities of forwarding data to REST Server 
5. capability of forward data to the MQTT broker 
6. capability of forwarding data to database

gamma version：beta version：
- [ ] command capability support

1. Command format definition
2. Command management
3. Command query interface
4. Command execution forwarding interface

- [ ] Event management capability support

1. Event format definition
2. Event storage capability
3. Event query interface
4. Event creation interface
5. Event deletion interface

- [ ] Upgrade capability support

1. Upgrade-related CRD design
2. Check the upgrade status.
3. Upgrade interface

- [ ] e2e test
