### ISSUE TITLE
Umbrella issue for test cases enhancement

### ISSUE THREAD

**Issue by vincentgoat** [kubeedge/kubeedge#4327]
## Description
We summarized some task items as follows for KubeEdge code quality testing, please comment with one or more items' names if you are interested to join.

### Unit Test
- [x] integrated Codecov into CI/CD -- @gy95 
#### Complete UT cases in the following directory to improve the coverage to at least 80%.
- [ ] kubeedge/cloud/pkg/admissioncontroller @gy95 
- [ ] kubeedge/cloud/pkg/cloudhub @wackxu 
  - kubeedge/cloud/pkg/cloudhub/servers/httpserver/updateconfig_test.go https://github.com/kubeedge/kubeedge/pull/4461 
- [ ] kubeedge/cloud/pkg/cloudstream @wackxu 
- [ ] kubeedge/cloud/pkg/csidriver
  - kubeedge/cloud/pkg/csidriver/uds_test.go https://github.com/kubeedge/kubeedge/pull/4446
- [ ] kubeedge/cloud/pkg/devicecontroller @RyanZhaoXB 
  - kubeedge/cloud/pkg/devicecontroller/manager/devicemodel_test.go https://github.com/kubeedge/kubeedge/pull/4467 
- [ ] kubeedge/cloud/pkg/dynamiccontroller @wackxu 
- [ ] kubeedge/cloud/pkg/edgecontroller @vincentgoat 
- [ ] kubeedge/cloud/pkg/nodeupgraderjobcontroller @gy95 
- [ ] kubeedge/cloud/pkg/router @gy95 
- [x] kubeedge/cloud/pkg/synccontroller @vincentgoat 
- [ ] kubeedge/edge/devicetwin @ksankeerth 
- [x] kubeedge/edge/pkg/edgehub -- @ksankeerth 
- [ ] kubeedge/edge/pkg/eventbus @Nageshbansal 
- [ ] kubeedge/edge/pkg/servicebus @gy95 
- [ ] kubeedge/edge/pkg/edgestream @fisherxu 
- [ ] kubeedge/edge/pkg/metamanager @Shelley-BaoYue 
  - kubeedge/edge/pkg/metamanager/client/nodestatus_test.go https://github.com/kubeedge/kubeedge/pull/4502 
- [ ] kubeedge/edge/pkg/edged @Shelley-BaoYue 
- [ ] kubeedge/keadm/cmd/keadm/app @gy95 
- [ ] kubeedge/pkg/metaserver @Shelley-BaoYue 
- [x] kubeedge/pkg/image @my-git9 
- [ ] kubeedge/pkg/stream @fisherxu 

### E2E Test / Integration Test
- [x] EdgeApplication and NodeGroup features @Congrool 
- [ ] Pods prober check
- [ ] Certificate rotation
- [ ] Meta Server list/watch operations
- [ ] Node Upgrade operations
- [ ] Deploy EdgeMesh for service access in the edge
- [ ] Use DMI with Mapper
- [ ] Device management
- [ ] Message delivered by Servicebus/Eventbus/REST
- [ ] Reliable message management in the module synccontroller
- [ ] Debugging operations of logs/exec in the module cloudstream/edgestream
- [ ] Metrics server

### Conformance Testing
- [x] Integrating conformance tests framework and the base conformance tests @wackxu @vincentgoat 
- [ ] Adding conformance tests of Devices and Rule/RuleEndpoint

**Comment by ksankeerth** [comment]
I'll write UT for kubeedge/edge/pkg/edgehub

**Comment by vincentgoat** [comment]
> I'll write UT for kubeedge/edge/pkg/edgehub

Thanks a ton!

**Comment by vincentgoat** [comment]
Test in local host and check coverage:
go test -v ./... -coverprofile=cover.out
gocov convert cover.out | gocov-xml > coverage.xml

**Comment by vincentgoat** [comment]
Integrating conformance tests framework and the base conformance tests: https://github.com/kubeedge/kubeedge/pull/4411

**Comment by Nageshbansal** [comment]
i want to work on the `kubeedge/edge/pkg/edgehub.` please assign it to me if no one is working on this

**Comment by vincentgoat** [comment]
> i want to work on the `kubeedge/edge/pkg/eventbus.` please assign it to me if no one is working on this

Great, sure.

**Comment by ksankeerth** [comment]
Hi @vincentgoat,
If nobody has picked "kubeedge/edge/devicetwin", then I can write unit tests. 
Thanks!

**Comment by vincentgoat** [comment]
> 

Great, thanks.

**Comment by vincentgoat** [comment]
> Hi @vincentgoat, If nobody has picked "kubeedge/edge/devicetwin", then I can write unit tests. Thanks!

Great, thanks.

**Comment by nox1134** [comment]
Hi @vincentgoat! If no one is working on `kubeedge/edge/pkg/eventbus`, I'd like to work on this. Please assign it to me.

**Comment by vincentgoat** [comment]
> Hi @vincentgoat! If no one is working on `kubeedge/edge/pkg/eventbus`, I'd like to work on this. Please assign it to me.

Thanks @nox1134

**Comment by 1Shubham7** [comment]
Hey @vincentgoat I have added tests covering `kubeedge/cloud/pkg/cloudstream` so if @wackxu is not working on that, kindly assign that work to me.

**Comment by 1Shubham7** [comment]
Also please assign me `kubeedge/pkg/stream` . I have started working on it :)
