### ISSUE TITLE
tracking issue for DMI in 2023

### ISSUE THREAD

**Issue by RyanZhaoXB** [kubeedge/kubeedge#4744]
Hello everyone! Here are the working items for DMI which we plan to do in sig device-iot in 2023. Please feel free to contact me or leave a message under this issue if you want to join us to  make some contributions for DMI. Thanks!

- [ ] propose the structure design of the Data Plane of DMI
- [ ] design and implement the access way of device data by pulling data from the data consumption application
- [ ] design and implement the access way of device data by pushing data to application or broker actively
- [ ] propose the solution for database interconnection
- [ ] propose the design of automatic device discovery and connection
- [ ] develop the  Development Framework of DMI which provide the protocol driver interface and help the developer to generate the Mapper which implementing DMI with one-line command
- [ ] provide a demo for interconnecting with EdgeX
- [ ] develop more mappers with DMI for more protocols and more languages
- [ ] Multi-node migration solution for edge devices based on KubeEdge device management interface DMI (implemented in Open Source Promotion Plan 2023）

**Comment by RyanZhaoXB** [comment]
Hi guys, the Multi-node migration solution for edge devices based on KubeEdge device management interface DMI has been made the project of Open Source Promotion Plan 2023 in #4763 .

**Comment by RyanZhaoXB** [comment]
the structure design of the Data Plane of DMI has been proposed in https://github.com/kubeedge/kubeedge/pull/4776/files
