### ISSUE TITLE
Umbrella Issue for KubeEdge e2e tests enhancement 

### ISSUE THREAD

**Issue by Shelley-BaoYue** [kubeedge/kubeedge#5178]
We have summarized some missing items in KubeEdge e2e test cases. You are welcome to help adding these e2e test cases to enhance the complete test capabilities for KubeEdge features. 

- [ ] node e2e tests for device plugin  
- [ ] node e2e tests for applications configured with probe 
- [ ] e2e tests for nodegroup and edgeapplication feature 
- [ ] e2e tests for device management 
- [ ] e2e tests for nodeupgrade feature 

Also, if you find there are other missing e2e tests need to be added, you can comment it under this issue.

**Comment by Shelley-BaoYue** [comment]
@cl2017 @wbc6080 Please help in refining the work items for device e2e testing.

**Comment by wbc6080** [comment]
OK, I will try to complete the e2e testing for device and mapper with @cl2017  
/assign @wbc6080
