### ISSUE TITLE
device model sync and consider the impact between namespaces

### ISSUE THREAD

**Issue by wbc6080** [kubeedge/kubeedge#5220]
**What happened**:
In the pr #5065 , we fixed device model sync problem. When added or deleted device, need to determine whether the device model needs to be sync to edgecore. However, we did not consider that device instance and device model are namespace-level resources. Resources with the same name in different namespaces may interfere with each other and require further repairs. 
**What you expected to happen**:
Fix device model sync problem with the same name resources in different namespaces
**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

- [x] We need to update dmi-api to fix this problem  #5251 
- [x] There may be similar problems in the **DeviceController** part, which need to be analyzed and solved. #5329
- [x] There may be similar problems in the **DMI** part, which need to be analyzed and solved. #5253 
- [x] There may be similar problems in the **Mapper Framework** part, which need to be analyzed and solved.  #5280 

**Environment**:
- Kubernetes version (use `kubectl version`):
- KubeEdge version(e.g. `cloudcore --version` and `edgecore --version`):
- <details><summary>Cloud nodes Environment:</summary>

  - Hardware configuration (e.g. `lscpu`):
  - OS (e.g. `cat /etc/os-release`):
  - Kernel (e.g. `uname -a`):
  - Go version (e.g. `go version`):
  - Others:

  </details>
- <details><summary>Edge nodes Environment:</summary>

  - edgecore version (e.g. `edgecore --version`):
  - Hardware configuration (e.g. `lscpu`):
  - OS (e.g. `cat /etc/os-release`):
  - Kernel (e.g. `uname -a`):
  - Go version (e.g. `go version`):
  - Others:

  </details>

**Comment by fisherxu** [comment]
Not sure whether edgecore/mapper need to fix for the device namespace.
cc @wbc6080 @cl2017 @luomengY

**Comment by wbc6080** [comment]
I compiled a list of components that might have similar problems that we could then analyze and resolve one by one. If there are other components that may have similar problems, you can also add them under the issue.

**Comment by wbc6080** [comment]
Please review these 4 PRs together, thank you.  @luomengY @cl2017 @WillardHu

**Comment by wbc6080** [comment]
Since all the above PRs have been merged, this issue will be closed.
