### ISSUE TITLE
Build the kubeedge/api repository and complete the code migration

### ISSUE THREAD

**Issue by wbc6080** [kubeedge/kubeedge#5474]
**What would you like to be added/modified**:

Build the kubeedge/api repository and complete the code migration

**Why is this needed**:

Since the current kubeedge api code is in the pkg/apis directory and does not form an independent repository, the entire kubeedge repo must be referenced when using the kubeedge api externally, which is relatively unreasonable.
Currently, we have submitted an application to establish an api repo https://github.com/kubeedge/community/issues/193. In order to successfully migrate the functions of the api to the new api repo, there are several things that need to be completed:

- [x] Migrate the contents of the current pkg/apis directory to staging/api  #5760  
- [x] Modify the way other parts of kubeedge refer to the API and complete debugging to ensure that kubeedge can run normally after migration. #5760
- [x] After the above steps are completed, remove all the contents of the original pkg/apis directory. #5760

**Comment by wbc6080** [comment]
In #5760, We have completed all the above work.
/close
