### ISSUE TITLE
Umbrella Issue for KubeEdge tests enhancement 

### ISSUE THREAD

**Issue by Shelley-BaoYue** [kubeedge/kubeedge#5562]
**What would you like to be added/modified**:

As KubeEdge undergoes version iterations, the testing work should also be updated and enhanced in sync with the requirements. This includes the following tasks:

- [ ] Support running Kubernetes conformance tests in release CI  
- [ ] Unit-Test Enhancement 
- [ ] e2e Tests Enhancement -- https://github.com/kubeedge/kubeedge/issues/5178
- [ ] Integration Test Enhancement

**Comment by ShivamJha2436** [comment]
Hey @Shelley-BaoYue, 
I'm eager to contribute to KubeEdge testing through the LFX program. 
My proposal focuses on enhancing the test suite in key areas:
1.  Integrating Kubernetes conformance tests in CI,
2.  Improving unit tests,
3.  Collaborating on e2e test enhancements (issue #5562), and 
4.  Strengthening integration tests. 
Let me know if you'd be interested in discussing this further.

**Comment by 1Shubham7** [comment]
Hey @Shelley-BaoYue,
This is Shubham, I am a contributor at CNCF Kyverno and have previously also contributed to CNCF ORAS. I am currently working as a technical writing intern at a startup called GeeksforGeeks where I write articles about DevOps and Kubernetes. I want to apply for LFX term 2 with KubeEdge and am really interested in this issue. I have some experience in writing E2E tests and am learning more and working on writing some E2E tests for KubeEdge (https://github.com/kubeedge/kubeedge/issues/5043). I have decent knowledge in golang and have been contributing to CNCF projects since 8 months now. I will keep on exploring the project and work on improving the test coverage and apply for LFX with this issue.

Thanks

**Comment by Stazz0** [comment]
Hello @Shelley-BaoYue, 
My name is Ashish Bhawel, and I'm a final-year Information Technology Engineering student at JEC, Jabalpur, India. I'm writing to express my interest in contributing to the KubeEdge project on improving test coverage (#5562) as part of the LFX Term 2 program.

While I'm little new to KubeEdge itself, I have some experience in writing E2E tests. I have started working on some E2E tests for KubeEdge (#5043) to further enhance my understanding of the project. Additionally, I possess a decent knowledge of Golang, Kubernetes and KubeEdge.

I'm highly motivated to participate in LFX Term 2 and believe my skills align well with this project's requirements. I'm eager to learn more about the specific testing needs and how I can best contribute.

I've also applied for Google Summer of Code (GSoC) this year, demonstrating my commitment to open-source contributions.

I'll continue to explore the project and work on improving the test coverage. I plan to formally submit my LFX application focusing on this issue shortly.

Thank you 
Sincerely,
Ashish Bhawel

**Comment by Shelley-BaoYue** [comment]
Hi, @1Shubham7  Thx for your contributions these days.  I've chosen you as the LFX term2 test cases enhancement mentee. How about getting start on this work?  Personally, I think it will be easier to start with unit test 😄

**Comment by 1Shubham7** [comment]
I am truly grateful to you @Shelley-BaoYue for selecting me as an LFX mentee. This opportunity means a lot to me, I will make sure to work hard and exceed your expectations. Thanks for acknowledging my contributions as well. Please do keep guiding me during the mentorship, I will get started will writing unit tests from today, I have my exam today, I will finish that up and get started.

Once again, thanks a lot Shelley, it really means a lot to me :)

**Comment by Shelley-BaoYue** [comment]
Haha, let's get started!  Feel free to communicate here if you have any question.

**Comment by Shelley-BaoYue** [comment]
@1Shubham7  It means that edgecore is not running properly. You can run make e2e in your local environment and check the edgecore log. 

BTW，I hope to continue to do some UT work in the future. Currently, the coverage can be viewed through https://app.codecov.io/gh/kubeedge/kubeedge. We need to improve the coverage of the cloud and edge directories as much as possible. : )

**Comment by 1Shubham7** [comment]
ok Shelley, checking it. BTW I didn't change any code in my local env and it showed that. also if UT is the priority for the project I will also focus on those. Also Please do give me feedback on how I have been doing so far in the mentorship, I have been giving 10 - 12 hours everyday almost everyday and I will surely improve this. I hope I am going decent for getting positive mid term evaluations :)

Also Shelley, I will have my exams for a week in August so I will not be able to be very active at that time (But I will make sure to give at least 5-6 hours a day) and will make sure to cover it up later:)

**Comment by Shelley-BaoYue** [comment]
@1Shubham7  If the local `make e2e` execution fails, you can use `journalctl -f -u edgecore.service` to find the reason through the edgecore logs. 

As for the timeline, I think you can arrange it freely.  You've been doing very well so far. 👍 Take it easy and participate in the LFX based on your own scheduleand. I would prefer that you can continuous participate in the community's work and also gain something from the community. 😄   

In terms of the work content, the community's target for UT is to achieve an 80% coverage rate (but this is not a requirement for you, feel free to supplement as much as possible), and you can learn about the e2e use cases related to the use of device plugins at the edge (you can refer to Kubernetes e2e test); I hope you can first learn and use KubeEdge, and during this process, identify areas that need optimization, including but not limited to code standards, documentation, and test cases.

**Comment by 1Shubham7** [comment]
Hey @Shelley-BaoYue, since we last talked I have written some more UTs and I was stuck at writing an e2e which now successfully works, one small mistake costed me hours :) I am still unable to run `make e2e` locally, I will discuss that later with you and other maintainers after trying once again.

[here's the PR](https://github.com/kubeedge/kubeedge/pull/5741), please also give your thoughts on my comment there about changes we can make in the code standards. I will continue working on UTs, e2e you discussed, learning more about and using KubeEdge.

**Comment by 1Shubham7** [comment]
Also @Shelley-BaoYue, midterm mentee evaluations were expected to be on 24th July but I didn't receive any mail yet so please look into it :)

**Comment by Shelley-BaoYue** [comment]
Hi, @1Shubham7  Thanks for your contributions in KubeEdge community. You can submit a issue at https://github.com/kubeedge/community/issues to become KubeEdge member 😄
