### ISSUE TITLE
Improve kubeedge api migration feature

### ISSUE THREAD

**Issue by wbc6080** [kubeedge/kubeedge#5801]
**What would you like to be added/modified**:
After completing the API code migration, some improvements still need to be done
**Why is this needed**:
After completing the kubeedge API code migration, some additional work is needed to improve the user experience, such as supplementing some documentation, building an API repo, etc. These tasks are tracked here. Some areas for improvement are listed below:

- [x] Add a README to the directory where the original api and apidoc functions are stored, indicating that we have moved the api to the staging directory. #5825 
- [x] Add a README file to the newly built api directory to indicate the main functions of this part. #5825 
- [x] Create a new api repo and synchronize the code in staging to the api repo. https://github.com/kubeedge/community/issues/193

**Comment by wbc6080** [comment]
I have listed here some improvements after API migration. If anyone else has suggestions for improvements, please comment here.
