### ISSUE TITLE
[EPIC] Enhance the keadm edge commands

### ISSUE THREAD

**Issue by WillardHu** [kubeedge/kubeedge#5940]
## What would you like to be added/modified:

- [x] Same node name check when join a node; https://github.com/kubeedge/kubeedge/pull/5965
- [x] Add prerun and postrun shell hooks for keadm edge commands;  https://github.com/kubeedge/kubeedge/pull/5946
- [ ] The batch-join command supprots sign in to edge nodes with the SSH private key; https://github.com/kubeedge/kubeedge/pull/5968
- [ ] The batch-join command supprots scp some files to edge nodes; ditto

### Same node name check when join a node

When we join two nodes with the same name, only one node will be registered in the cloud, and then the status of the nodes will be affected by each other. This is due to the logic of EdgeCore, EdgeCore registers nodes to the cloud when it starts, when EdgeCore restarts, it cannot become a new registered node. Therefore, the logic in the cloud is that if the node exists, no processing will be performed.

We need to call the https server of cloudcore to verify whether the node name already exists when executing the `keadm join` command. Calling the api-server will increase the complexity of executing `keadm join`, because we need to obtain kubeconf or token to call the api-server.

Kubeadm will also check for duplicate node names when joining a node. Refer to: https://github.com/kubernetes/kubernetes/blob/c6669ea7d61af98da3a2aa8c1d2cdc9c2c57080a/cmd/kubeadm/app/cmd/phases/join/kubelet.go#L214

### Add prerun and postrun shell hooks for keadm edge commands

Previously, we discussed in the issue #5745 about automatically installing the container runtime before executing the `keadm join` command. The conclusion is that there are many implementations and versions of container runtimes, and it will be a huge effort for the KubeEdge community to maintain them.

Therefore, we thought of using prerun and postrun shell hooks to handle container runtime installation and uninstallation, as well as more flexible applications. E.g., `keadm join --preun install-constainerd.sh`, `keadm reset --postrun uninstall-containerd.sh`.

### Enhance the batch-join command 

We have just implemented a Bate version of the `keadm batchjoin` command to batch join edge nodes.
- issue: https://github.com/kubeedge/kubeedge/issues/5590
- proposal: https://github.com/kubeedge/kubeedge/blob/master/docs/proposals/batch-node-access.md
- pr: https://github.com/kubeedge/kubeedge/pull/5889

#### Supprots login to edge nodes with the SSH private key

Currently, we implement SSH sign in to the node with username / password, but many scenarios use a private key to SSH sign in to the node, so we need to provide this method.

#### Supprots scp some files to edge nodes

Currently, each managed node needs to re-download the installation packages from Internet, which increases the risk of failure, and many users are offline. Therefore, we need to provide scp to transfer files from the management node to the managed nodes.
