### ISSUE TITLE
Contributor Experience Improvement Tracking Issue

### ISSUE THREAD

**Issue by kevin-wangzefeng** [kubeedge/kubeedge#944]
One of the top priority work to do duing the next few months is to improve contributor experience, help more new contributors get on board.

This issue is to track the things need to be done. (To have an overview of where we are and what to be done, some docs already exist also included.)

### General

- [ ] [Docs] Separate user manual and contributor guide docs, TBD.

- [ ] [Docs] Governance doc, general introduction of how the community is operated, including SIG/WG setup etc.

- [x] [Docs] [Membership guide](https://github.com/kubeedge/kubeedge/blob/master/docs/getting-started/community-membership.md)

- [x] [Docs] [Code of Conduct](https://github.com/kubeedge/kubeedge/blob/master/CODE_OF_CONDUCT.md)

### Releases

- [ ] [Docs] Release lifecycle, [draft doc here](https://docs.google.com/document/d/1vZ8ZLOUxo29vaoB9rnn_RVopMcmXkZpW77F0FFJKbf8/edit?usp=sharing)

- [ ] [Tooling] Release automation: automate the process of making a new release, #992.

- [ ] [Docs] Usage of Milestone and Projects view. #1001

### Feature guide

- [x] [Docs] [Feature lifecycle](https://github.com/kubeedge/kubeedge/blob/master/docs/getting-started/feature-lifecycle.md) (maturity development stages)

- [ ] [Docs] Proposing Enhancements (features), TBD.

- [ ] [Docs] How to write Enhancement (KEP) guide, TBD.

### Developer self-service
- [x] [Docs] [local env setup (for development)](https://github.com/kubeedge/kubeedge/blob/master/docs/setup/setup.md)

- [ ] [Docs] PR flow, TBD.

- [ ] [Docs] Debugging guide, TBD.

- [x] [Docs] [Reporting Bugs](https://github.com/kubeedge/kubeedge/blob/master/docs/getting-started/reporting_bugs.md)

- [x] [Tooling] Improve CI status visibility, ref: https://github.com/kubeedge/kubeedge/issues/810

- [ ] [Tooling] Speed up CI checking, e.g. #951(optimization / refactor e2e).

- [ ] [Tooling] enable more prow functions, e.g. `retest`, TBD.

- [x] [Tooling] Enable document preview on pull requests (if /docs is changed). Ref: https://github.com/kubeedge/kubeedge/issues/944#issuecomment-591298958

**Comment by sids-b** [comment]
Please feel free to take-up any of the missing documents or improve the existing doc. 

Please ping here if someone is working on any doc to avoid duplication of work. Thanks :)

**Comment by subpathdev** [comment]
I will take  '[Tooling] Release automation: automate the process of making a new release, TBD.'
and  '[Tooling] Improve CI status visibility, ref: #810'

**Comment by subpathdev** [comment]
please add issue #951 (optimization / refactor e2e to this list)

**Comment by rohitsardesai83** [comment]
> please add issue #951 (optimization / refactor e2e) to this list

maybe it indirectly addresses [Tooling] Speed up CI checking, TBD ?

**Comment by kevin-wangzefeng** [comment]
We can now preview document changes on pull requests!

An example here: https://github.com/kubeedge/kubeedge/pull/1501
![image](https://user-images.githubusercontent.com/6914660/75325680-3123aa80-58b4-11ea-9061-13076731378e.png)
