### ISSUE TITLE
CRD validation umbrella issues

### ISSUE THREAD

**Issue by chendave** [kubeedge/kubeedge#963]
* [x] Enable external admission webhook framework  https://github.com/kubeedge/kubeedge/pull/933

* [ ]  Reject protocol configs for protocols other than OPC UA , Modbus and Bluetooth https://github.com/kubeedge/kubeedge/issues/826

* [ ] Allow deletion of device model if no devices are referring to it  https://github.com/kubeedge/kubeedge/issues/827

* [x] device model property type can be only string or int64. Other types are not supported.
https://github.com/kubeedge/kubeedge/issues/823

* [x] creation of DeviceModel should fail if there is any misconfiguration https://github.com/kubeedge/kubeedge/issues/845

* [ ] Integration / unit test for admission webhook which cover all the above cases.

**Comment by rohitsardesai83** [comment]
:+1:

**Comment by chendave** [comment]
@rohitsardesai83 

In this PR https://github.com/kubeedge/kubeedge/pull/984, I have added some validation against `devicemodel`, you can see there additional properties are not rejected, I think even we have enabled the webhook, we still don't have effect way or no need to reject the additional properties.

Actually, I don't think we need to do that, as K8S point it out, there is no need to do that for the sake of compatibility, instead, we can reject the operation if no desired properties has been defined, take `devicemodel` for example, if one type of Int or String has been defined, we should be good even there is additional properties given the schema, actually, it is no harm to allow this behavior.

We can do the same thing for device `protocols` as well, what do you think? 

cc @fisherxu  @sids-b @kevin-wangzefeng
